# Generated by Django 3.2.8 on 2022-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.BigIntegerField(default=0, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('fb', models.URLField(max_length=500, null=True)),
                ('insta', models.URLField(max_length=500, null=True)),
                ('twitter', models.URLField(max_length=500, null=True)),
                ('linkedin', models.URLField(max_length=500, null=True)),
                ('githuburl', models.URLField(max_length=500, null=True)),
                ('stackoverflow', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('completedDate', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('web', 'web'), ('android', 'android'), ('desktop', 'desktop'), ('blockchain', 'blockchain')], max_length=200, null=True)),
            ],
        ),
    ]
