# Generated by Django 3.2.8 on 2022-03-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
