# Generated by Django 3.2.8 on 2022-03-06 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_alter_project_completeddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200, null=True)),
                ('institute', models.CharField(max_length=200, null=True)),
                ('marks', models.IntegerField(default=0, null=True)),
                ('completedDate', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ssc', 'ssc'), ('hssc', 'hssc'), ('bachelors', 'bachelors'), ('masters', 'masters'), ('phd', 'phd'), ('experience', 'experience')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='completedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
