# Generated by Django 3.2.8 on 2022-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20220307_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('ssc', 'ssc'), ('hssc', 'hssc'), ('bachelors', 'bachelors'), ('masters', 'masters'), ('phd', 'phd'), ('other', 'other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(choices=[('pre-medical', 'pre-medical'), ('pre-engineering', 'pre-engineering'), ('pre-computer science', 'pre-computer science'), ('arts', 'arts'), ('sociology', 'sociology'), ('humanity', 'humanity'), ('other', 'other')], max_length=200, null=True),
        ),
    ]
