# Generated by Django 3.2.8 on 2022-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20220307_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(default='a software engineer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(choices=[('pre-medical', 'pre-medical'), ('pre-engineering', 'pre-engineering'), ('pre-computer science', 'pre-computer science'), ('arts', 'arts'), ('software engineering', 'software engineering'), ('sociology', 'sociology'), ('humanity', 'humanity'), ('other', 'other')], max_length=200, null=True),
        ),
    ]
